# This is a basic workflow to help you get started with Actions

name: Documentation Generation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: gh-pages
      # Runs a single command using the runners shell
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
      
    - name: Merge recent changes
      run: |
        echo "Merging recent changes"
        git config --global user.name "kinoar"
        git config --global user.email "kinarose@gmail.com"
        git fetch
        git pull
        git branch
        git merge master || true
        git commit -m "Update document classes" || true
      
      # Runs a single command using the runners shell
    - name: npm install
      run: npm install
      # Install Lix Globally
    - name: install lix globally
      run: npm install --global lix
      # Downloads lix dependencies
      
    - name: lix download
      run: lix download

    # Runs a single command using the runners shell
    - name: Generate Documentation
      run: npm run gendoc
      
      # Runs a single command using the runners shell
    - name: Create Documentation
      run: npm run createdoc
    - name: Push Doc Changes To Branch
      run: |
        echo "Pushing to Gh-pages"
        git config --global user.name "kinoar"
        git config --global user.email "kinarose@gmail.com"
        git add -A || true
        git commit -m "Update documentation website" || true
        git push || true

